SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPham](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ma] [varchar](255) NULL,
	[ten] [varchar](255) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SanPham] ADD PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


-- sql luyen tap 

CREATE TABLE sinh_vien(
    ma_sinh_vien VARCHAR(50) PRIMARY KEY,
    ten_sinh_vien VARCHAR(50),
    ten_lop VARCHAR(50),
    gioi_tinh INT
)
